param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C - SPY Debugger, as an aid to preparing a command line for running
# the cspybat command line utility using the appropriate settings.
#
# Note that this file is generated every time a new debug session
# is initialized, so you may want to move or rename the file before
# making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the name of this batch file, followed
# by the name of the debug file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C - SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "C:\IAR8.50.1\common\bin\cspybat" -f "C:\Users\nxf55062\Documents\MCU_SDK\RT600\SDK_2.8.0_EVK-MIMXRT685_RC2_0\boards\evkmimxrt685\dsp_examples\eight_channel_dmic_i2s_playback\cm33\iar\settings\eight_channel_dmic_i2s_playback.flash_debug.general.xcl" --backend -f "C:\Users\nxf55062\Documents\MCU_SDK\RT600\SDK_2.8.0_EVK-MIMXRT685_RC2_0\boards\evkmimxrt685\dsp_examples\eight_channel_dmic_i2s_playback\cm33\iar\settings\eight_channel_dmic_i2s_playback.flash_debug.driver.xcl" 
}
else
{
& "C:\IAR8.50.1\common\bin\cspybat" -f "C:\Users\nxf55062\Documents\MCU_SDK\RT600\SDK_2.8.0_EVK-MIMXRT685_RC2_0\boards\evkmimxrt685\dsp_examples\eight_channel_dmic_i2s_playback\cm33\iar\settings\eight_channel_dmic_i2s_playback.flash_debug.general.xcl" --debug_file=$debugfile --backend -f "C:\Users\nxf55062\Documents\MCU_SDK\RT600\SDK_2.8.0_EVK-MIMXRT685_RC2_0\boards\evkmimxrt685\dsp_examples\eight_channel_dmic_i2s_playback\cm33\iar\settings\eight_channel_dmic_i2s_playback.flash_debug.driver.xcl" 
}
